#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "${REPO_ROOT}"

REMOTE="${REMOTE:-origin}"
CURRENT_BRANCH="$(git branch --show-current || true)"
BRANCH="${BRANCH:-${CURRENT_BRANCH:-main}}"
RUN_TP4="${RUN_TP4:-1}"
RUN_TP3="${RUN_TP3:-1}"
PUBLISH_MODE="${PUBLISH_MODE:-release}"
USE_LFS="${USE_LFS:-1}"
COMMIT_MESSAGE="${COMMIT_MESSAGE:-data: add cloud output handoff}"
RUN_STAMP="${RUN_STAMP:-$(date -u +%Y%m%dT%H%M%SZ)}"
RELEASE_TAG="${RELEASE_TAG:-tp4-outputs-${RUN_STAMP}}"
RELEASE_TITLE="${RELEASE_TITLE:-TP4 simulation outputs ${RUN_STAMP}}"
RELEASE_PART_SIZE="${RELEASE_PART_SIZE:-1900m}"

SYSTEM2_ROOT="outputs/system2-sweeps/system2-tp4-final"
TP3_ROOT="outputs/tp3-reference/tp3-final-grid"
SUMMARY_PATH="outputs/cloud-run-summary-${RUN_STAMP}.txt"
ASSET_ROOT="outputs/release-assets/${RUN_STAMP}"
CHECKSUM_PATH="${ASSET_ROOT}/SHA256SUMS.txt"
RELEASE_NOTES_PATH="${ASSET_ROOT}/release-notes.md"

fail() {
  echo "ERROR: $*" >&2
  exit 1
}

ensure_clean_tracked_state() {
  git diff --quiet || fail "Tracked files have unstaged changes before the cloud run."
  git diff --cached --quiet || fail "The index has staged changes before the cloud run."

  local unexpected_untracked
  unexpected_untracked="$(git status --short --untracked-files=all | grep -vE '^\?\? outputs/' || true)"
  if [[ -n "${unexpected_untracked}" ]]; then
    echo "${unexpected_untracked}" >&2
    fail "Unexpected untracked files exist outside outputs/. Commit or remove them first."
  fi
}

ensure_lfs_ready() {
  if [[ "${PUBLISH_MODE}" != "lfs" ]]; then
    return
  fi
  if [[ "${USE_LFS}" != "1" ]]; then
    return
  fi
  git lfs version >/dev/null 2>&1 || fail "Git LFS is required. Install/enable git-lfs or rerun with USE_LFS=0 after checking file sizes."
  git lfs install --local >/dev/null
}

ensure_release_ready() {
  if [[ "${PUBLISH_MODE}" != "release" ]]; then
    return
  fi
  gh --version >/dev/null 2>&1 || fail "GitHub CLI is required for PUBLISH_MODE=release."
  gh auth status >/dev/null 2>&1 || fail "GitHub CLI is not authenticated."
  tar --version >/dev/null 2>&1 || true
}

run_and_log() {
  local label="$1"
  local log_path="$2"
  shift 2
  mkdir -p "$(dirname "${log_path}")"
  {
    echo "# ${label}"
    echo "started_at_utc=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "command=$*"
    "$@"
    echo "finished_at_utc=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  } >"${log_path}" 2>&1
  echo "${label} log: ${log_path}"
}

write_summary() {
  mkdir -p outputs
  {
    echo "run_stamp=${RUN_STAMP}"
    echo "git_head=$(git rev-parse HEAD)"
    echo "branch=${BRANCH}"
    echo "run_tp4=${RUN_TP4}"
    echo "run_tp3=${RUN_TP3}"
    echo "publish_mode=${PUBLISH_MODE}"
    if [[ "${PUBLISH_MODE}" == "release" ]]; then
      echo "release_tag=${RELEASE_TAG}"
    fi
    echo
    echo "# Sizes"
    du -sh "${SYSTEM2_ROOT}" 2>/dev/null || true
    du -sh "${TP3_ROOT}" 2>/dev/null || true
    echo
    echo "# File counts"
    find "${SYSTEM2_ROOT}" -type f 2>/dev/null | wc -l | awk '{print "system2_files=" $1}'
    find "${TP3_ROOT}" -type f 2>/dev/null | wc -l | awk '{print "tp3_files=" $1}'
    echo
    echo "# Files over 95 MiB"
    find "${SYSTEM2_ROOT}" "${TP3_ROOT}" -type f -size +95M -print 2>/dev/null || true
  } >"${SUMMARY_PATH}"
  echo "Summary: ${SUMMARY_PATH}"
}

stage_lfs_outputs() {
  local roots_to_add=()
  if [[ "${RUN_TP4}" == "1" ]]; then
    roots_to_add+=("${SYSTEM2_ROOT}")
  fi
  if [[ "${RUN_TP3}" == "1" ]]; then
    roots_to_add+=("${TP3_ROOT}")
  fi
  roots_to_add+=("${SUMMARY_PATH}")

  if [[ "${USE_LFS}" != "1" ]]; then
    local oversized
    oversized="$(find "${roots_to_add[@]}" -type f -size +95M -print 2>/dev/null || true)"
    if [[ -n "${oversized}" ]]; then
      echo "${oversized}" >&2
      fail "Found files over 95 MiB and USE_LFS=0. Do not push these with normal Git."
    fi
  fi

  git add -f "${roots_to_add[@]}"
}

hash_file() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1"
  else
    shasum -a 256 "$1"
  fi
}

archive_tree() {
  local label="$1"
  local source_path="$2"
  local output_prefix="${ASSET_ROOT}/${label}.tar.gz.part-"

  if [[ ! -d "${source_path}" ]]; then
    echo "Skipping missing ${source_path}"
    return
  fi

  mkdir -p "${ASSET_ROOT}"
  echo "Archiving ${source_path} into split assets with part size ${RELEASE_PART_SIZE}."
  tar -czf - "${source_path}" | split -b "${RELEASE_PART_SIZE}" - "${output_prefix}"
}

write_release_notes() {
  mkdir -p "${ASSET_ROOT}"
  {
    echo "# ${RELEASE_TITLE}"
    echo
    echo "Generated by Codex Cloud from commit \`$(git rev-parse HEAD)\`."
    echo
    echo "## Contents"
    echo
    if [[ "${RUN_TP4}" == "1" ]]; then
      echo "- TP4 System 2 final sweep: \`${SYSTEM2_ROOT}\`"
    fi
    if [[ "${RUN_TP3}" == "1" ]]; then
      echo "- TP3 reference sweep: \`${TP3_ROOT}\`"
    fi
    echo
    echo "## Restore"
    echo
    echo "\`\`\`bash"
    echo "mkdir -p outputs/downloaded-${RUN_STAMP}"
    echo "gh release download ${RELEASE_TAG} --dir outputs/downloaded-${RUN_STAMP}"
    echo "cd outputs/downloaded-${RUN_STAMP}"
    echo "cat system2-tp4-final.tar.gz.part-* > system2-tp4-final.tar.gz 2>/dev/null || true"
    echo "cat tp3-final-grid.tar.gz.part-* > tp3-final-grid.tar.gz 2>/dev/null || true"
    echo "tar -xzf system2-tp4-final.tar.gz -C ../.. 2>/dev/null || true"
    echo "tar -xzf tp3-final-grid.tar.gz -C ../.. 2>/dev/null || true"
    echo "\`\`\`"
  } >"${RELEASE_NOTES_PATH}"
}

prepare_release_assets() {
  rm -rf "${ASSET_ROOT}"
  mkdir -p "${ASSET_ROOT}"

  if [[ "${RUN_TP4}" == "1" ]]; then
    archive_tree "system2-tp4-final" "${SYSTEM2_ROOT}"
  fi
  if [[ "${RUN_TP3}" == "1" ]]; then
    archive_tree "tp3-final-grid" "${TP3_ROOT}"
  fi

  write_release_notes
  : >"${CHECKSUM_PATH}"
  find "${ASSET_ROOT}" -type f ! -name "SHA256SUMS.txt" -print0 \
    | sort -z \
    | while IFS= read -r -d '' asset; do
        hash_file "${asset}" >>"${CHECKSUM_PATH}"
      done

  git add -f "${SUMMARY_PATH}" "outputs/script-tests-${RUN_STAMP}.log" "${CHECKSUM_PATH}" "${RELEASE_NOTES_PATH}"
}

create_release() {
  local assets=()
  while IFS= read -r -d '' asset; do
    assets+=("${asset}")
  done < <(find "${ASSET_ROOT}" -type f -print0 | sort -z)

  if [[ "${#assets[@]}" -eq 0 ]]; then
    fail "No release assets were produced."
  fi

  gh release create "${RELEASE_TAG}" "${assets[@]}" \
    --target "${BRANCH}" \
    --title "${RELEASE_TITLE}" \
    --notes-file "${RELEASE_NOTES_PATH}"
  gh release view "${RELEASE_TAG}" --json url --jq .url
}

echo "Preparing cloud output run on ${BRANCH}."
ensure_clean_tracked_state
ensure_lfs_ready
ensure_release_ready

git fetch "${REMOTE}" "${BRANCH}"
git merge --ff-only "${REMOTE}/${BRANCH}"

mkdir -p "${SYSTEM2_ROOT}" "${TP3_ROOT}"
run_and_log "script tests" "outputs/script-tests-${RUN_STAMP}.log" \
  python3 -m unittest discover -s scripts -p 'test_*.py'
git add -f "outputs/script-tests-${RUN_STAMP}.log"

if [[ "${RUN_TP4}" == "1" ]]; then
  run_and_log "TP4 System 2 full sweep" "${SYSTEM2_ROOT}/cloud-run-${RUN_STAMP}.log" \
    python3 scripts/run_system2_sweep.py --execute
fi

if [[ "${RUN_TP3}" == "1" ]]; then
  run_and_log "TP3 reference sweep" "${TP3_ROOT}/cloud-run-${RUN_STAMP}.log" \
    python3 scripts/run_tp3_reference_sweep.py --execute
fi

write_summary

if [[ "${PUBLISH_MODE}" == "release" ]]; then
  prepare_release_assets
elif [[ "${PUBLISH_MODE}" == "lfs" ]]; then
  stage_lfs_outputs
else
  fail "Unknown PUBLISH_MODE=${PUBLISH_MODE}. Use release or lfs."
fi

if git diff --cached --quiet; then
  echo "No output changes to commit."
  exit 0
fi

git status --short
git commit -m "${COMMIT_MESSAGE}"
git push "${REMOTE}" "HEAD:${BRANCH}"
echo "Pushed handoff commit to ${REMOTE}/${BRANCH}."

if [[ "${PUBLISH_MODE}" == "release" ]]; then
  create_release
  echo "Uploaded output assets to GitHub Release ${RELEASE_TAG}."
fi
